Add BUFF_STACKS_GTE criteria check
marisa-ashkandi/tbcsim pull request #97
Opened 2021-09-10 07:20 UTC by CyberQuackGames

Added the opposite of BUFF_STACKS_LTE. At the moment this has a use case with Shadow Weaving stacks for trinket / ability usage.

2021-09-15 05:49 UTC, marisa-ashkandi requested changes

2021-09-15 05:49 UTC, marisa-ashkandi commented on src/commonMain/kotlin/sim/rotation/criteria/BuffStacksGte.kt
> +        return state == null || state.currentStacks >= stacks
A missing buff (aka `null` `state` value) should return `false` for this criterion.

2021-09-18 18:08 UTC, CyberQuackGames commented
@marisa-ashkandi Thanks for review and catch there, should be good now.

2021-09-21 04:07 UTC, marisa-ashkandi approved these changes

2021-09-21 04:07 UTC, merged